{% set name = "libusb1" %}
{% set version = "3.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/libusb1-{{ version }}.tar.gz
  sha256: 4ee9b0a55f8bd0b3ea7017ae919a6c1f439af742c4a4b04543c5fd7af89b828c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4

test:
  imports:
    - usb1
    - usb1.__pyinstaller
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/vpelletier/python-libusb1
  summary: Pure-python wrapper for libusb-1.0
  license: LGPL-2.1-or-later
  license_file: COPYING.LESSER

extra:
  recipe-maintainers:
    - ickc
